name: Build prod

on:
  push:
    branches:
      - main
runs:
  using: 'node16'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-1'   # optional: defaults to us-east-1

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Zip Folder
#       run: zip -r release.zip .
#     - name: Release to Github
#       run: ls -la
#     - name: Upload S3
#       uses: hkusu/s3-upload-action@v2
#       with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#           aws-region: 'ap-northeast-1'
#           aws-bucket: 'laravel-ec-bucket'
#           file-path: 'release.zip'
