name: Build prod

on:
  push:
    branches:
      - main

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: true
      #     token: ${{ secrets.TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Upload to s3
        run : |
          sh .github/workflows/upload_to_s3.sh -p
      # ./.github/scripts/build.sh