name: Build prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release.zip .
    - name: Release to Github
      run: ls -la
    - name: Upload S3
      uses: shallwefootball/upload-s3-action@v1.2.0
      with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: laravel-ec-bucket
          source_dir: release.zip
