name: Build prod

on:
  push:
    branches:
      - main

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: true
      #     token: ${{ secrets.TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: action-zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r github_to_s3.zip /home/runner/work/laravel_study/laravel_study

      - name: Upload to s3
        run : |
          aws s3 sync /home/runner/work/laravel_study/laravel_study/github_to_s3.zip s3://laravel-ec-bucket
