name: Build prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release.zip .
    - name: Release to Github
      run: ls -la
    - name: Upload S3
      using: 'node16'
      uses: hkusu/s3-upload-action@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: 'ap-northeast-1'
          aws-bucket: 'laravel-ec-bucket'
          file-path: 'release.zip'
